classes_names = {
    0 : "Speed Limit (20)",
    1 : "Speed Limit (30)",
    2 : "Speed Limit (50)",
    3 : "Speed Limit (60)",
    4 : "Speed Limit (70)",
    5 : "Speed Limit (80)",
    6 : "End of Zone with Speed Limit (80)",
    7 : "Speed Limit (100)",
    8 : "Speed Limit (120)",
    9 : "Overtaking Prohibited",
    10 : "Overtaking Prohibited for Trucks",
    11 : "Crossroad",
    12 : "Begin of a Priority Road",
    13 : "Give way to all drivers",
    14 : "Stop",
    15 : "Entry Prohibited",
    16 : "Trucks Prohibited",
    17 : "Road with One-Way Traffic (Entry Prohibited)",
    18 : "Warning for Danger",
    19 : "Curve to the Left",
    20 : "Curve to the Right",
    21 : "Double Curve Left-Right",
    22 : "Bad Road Surface",
    23 : "Slippery Road Surface",
    24 : "Road Narrowing on the Right",
    25 : "Roadworks",
    26 : "Traffic Light",
    27 : "Pedestrians Prohibited",
    28 : "Children",
    29 : "Cyclists",
    30 : "Snow",
    31 : "Deer",
    32 : "National Speed Limit Applies",
    33 : "Turning Right Mandatory",
    34 : "Turning Left Mandatory",
    35 : "Driving Straight Ahead Mandatory",
    36 : "Driving Straight Ahead or Turning Right Mandatory",
    37 : "Driving Straight Ahead or Turning Left Mandatory",
    38 : "Passing Right Mandatory",
    39 : "Passing Left Mandatory",
    40 : "Mandatory Direction of the Roundabout",
    41 : "Overtaking Prohibited Over",
    42 : "Overtaking Prohibited for Trucks"
}